version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql-config:/etc/mysql/conf.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - 8080:80
