name: Deploy to Railway

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 20.1.0
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Dependencies'
        run: npm install --omit=dev
      - name: Update Database
        run: npm run db:push
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up --service=fastify-market-backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
